import Body from '@/components/Body'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <main className='flex flex-col items-center h-screen justify-center'>
      <Head>
        <title>Google</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Body />
      <Footer />
    </main>
  )
}
