import Body from '@/components/Body'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { useTheme } from 'next-themes'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'

export default function Home() {
  const [mounted, setMounted] = useState(false)
  const { systemTheme, theme } = useTheme()
  const currentTheme = theme === 'system' ? systemTheme : theme

  useEffect(() => {
    setMounted(true)
  }, [])

  if (!mounted) return null

  return (
    <main className='flex flex-col items-center h-screen justify-center dark:bg-[#202124]'>
      <Head>
        <title>Google</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/logo.png' />
      </Head>
      <Header currentTheme={currentTheme} />
      <Body currentTheme={currentTheme} />
      <Footer />
    </main>
  )
}
